apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 242766236021.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 242766236021.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 718c7b4d
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
